name: PUB

on:
  push:
    tags:
      - 'v*'

env:
  ENTANDO_OPT_USE_PPL_TAG: "v1.4.2"
  ENTANDO_OPT_DATA_REPO: "${{ secrets.ENTANDO_OPT_DATA_REPO }}"
  ENTANDO_OPT_DATA_REPO_TOKEN: "${{ secrets.ENTANDO_OPT_DATA_REPO_TOKEN }}"
  ENTANDO_OPT_ENVIRONMENT_NAMES: "${{ secrets.ENTANDO_OPT_ENVIRONMENT_NAMES }}"
  ENTANDO_OPT_FEATURES: "${{ secrets.ENTANDO_OPT_FEATURES }}"
  ENTANDO_OPT_GLOBAL_FEATURES: "${{ secrets.ENTANDO_OPT_GLOBAL_FEATURES }}"
  ENTANDO_OPT_LOG_LEVEL: "${{ secrets.ENTANDO_OPT_LOG_LEVEL }}"
  ENTANDO_OPT_CUSTOM_ENV: "${{ secrets.ENTANDO_OPT_CUSTOM_ENV }}"
  PPL_CONTEXT: ${{ toJson(github) }}
  LOCAL_CLONE_DIR: "local-checkout"


jobs:
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # PUBLICATION

  publication:
    outputs:
      POST_PUB_DOCKER_SCAN: ${{ steps.START.outputs.POST_PUB_DOCKER_SCAN }}
      POST_DEP_TESTS: ${{ steps.START.outputs.POST_DEP_TESTS }}
    env:
      ENTANDO_BOT_TOKEN: ${{ secrets.ENTANDO_BOT_TOKEN }}
      PUBLIC_URL: "/app-builder"
      DOMAIN: "/entando-de-app"
      USE_MOCKS: "false"
      CI: "false"
      COMPONENT_REPOSITORY_UI_ENABLED: "true"
      KEYCLOAK_ENABLED: "true"
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14

#      - name: "Cache NPM Packages"
#        id: package-cache
#        uses: actions/cache@v2
#        with:
#          path: ~/.npm
#          key: ${{ runner.os }}-npm
          
      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build --production

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # List of Docker Images to use as a base name for tags
          images: |
            entando/app-builder
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr,value={{base_ref}}
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,event=pr,value={{base_ref}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ENTANDO_OPT_DOCKER_USERNAME }}
          password: ${{ secrets.ENTANDO_OPT_DOCKER_PASSWORD }}

      - name: Login to RHT
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ENTANDO_RHT_DOCKER_REGISTRY }}
          username: ${{ secrets.ENTANDO_RHT_DOCKER_USERNAME }}
          password: ${{ secrets.ENTANDO_RHT_DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
